version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/FinalRPO
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Maks2552@
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "8081:8080"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:16-alpine
    container_name: rpo3_postgres
    restart: always
    environment:
      POSTGRES_DB: FinalRPO
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Maks2552@
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: